version: 2

models:
- name: under_granular_codes
  description: "Checks for ICD codes that do not meet the granular requirements for their version."
  columns:
    - name: icd_code
      description: "The ICD code being validated."
      tests:
        - not_null

- name: missing_diagnoses
  description: "Checks for missing ICD codes in the diagnosis table."
  columns:
    - name: icd_code
      description: "The ICD code, which should not be null."
      tests:
        - not_null

- name: duplicate_diagnoses
  description: "Checks for duplicate diagnoses based on subject_id and icd_code."
  columns:
    - name: subject_id
      description: "The subject ID for the diagnosis."
    - name: icd_code
      description: "The ICD code for the diagnosis."

- name: missing_subject_ids
  description: "Checks for invalid subject IDs in the diagnosis table."
  columns:
    - name: subject_id
      description: "The subject ID, which should not be null or empty."
      tests:
        - not_null