dbt_etl_pipeline:
  outputs:
    dev:
      dbname: etl_test
      host: postgres
      pass: postgres
      port: 5432
      schema: omop_cdm
      threads: 1
      type: postgres
      user: postgres
  target: dev