dbt_etl_pipeline:
  outputs:
    dev:
      dbname: etl_test
      host: localhost
      pass: postgres
      port: 5432
      schema: mimic_iv_ed
      threads: 1
      type: postgres
      user: postgres
  target: dev