dbt_etl_pipeline:
  outputs:
    dev:
      dbname: wsi_svs
      host: localhost
      pass: postgres
      port: 5432
      schema: raw_wsi_metadata
      threads: 1
      type: postgres
      user: postgres
  target: dev