dbt_etl_pipeline:
target: dev
outputs:
  seed_db:
    type: postgres
    threads: 1
    host: localhost
    port: 5432
    user: postgres
    pass: postgres
    dbname: raw_data
    schema: mimic_iv_ed
  target_db:
    type: postgres
    threads: 1
    host: localhost
    port: 5432
    user: postgres
    pass: postgres
    dbname: processed_data
    schema: omop_cdm
